name: Build and Publish
on: [ push, pull_request ]
jobs:
  build:
    name: Android simple CI
    runs-on: ubuntu-latest
    steps:

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Fetch Sources
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Run tests
        run: ./gradlew test

      - name: Build apk
        if: github.ref == 'refs/heads/master'
        run: ./gradlew assembleRelease

# todo run lint, detekt
# todo run code coverage
# todo sign/upload to firebase if needed